//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.NetTcp.BattleNet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Battle.net", ConfigurationName="BattleNet.ICalculator")]
    public interface ICalculator {
        
        // CODEGEN: Generating message contract since the wrapper name (CalculatorRequest) of message AddRequest does not match the default value (Add)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/ICalculator/Add", ReplyAction="http://Battle.net/ICalculator/AddResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.AddResponse Add(global::Microsoft.Samples.NetTcp.BattleNet.AddRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CalculatorRequest) of message DivideRequest does not match the default value (Divide)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/ICalculator/Divide", ReplyAction="http://Battle.net/ICalculator/DivideResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.DivideResponse Divide(global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CalculatorRequest) of message MultiplyRequest does not match the default value (Multiply)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/ICalculator/Multiply", ReplyAction="http://Battle.net/ICalculator/MultiplyResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.MultiplyResponse Multiply(global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (CalculatorRequest) of message SubtractRequest does not match the default value (Subtract)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/ICalculator/Subtract", ReplyAction="http://Battle.net/ICalculator/SubtractResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.SubtractResponse Subtract(global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public AddRequest() {
        }
        
        public AddRequest(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double result;
        
        public AddResponse() {
        }
        
        public AddResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class DivideRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public DivideRequest() {
        }
        
        public DivideRequest(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class DivideResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double result;
        
        public DivideResponse() {
        }
        
        public DivideResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class MultiplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public MultiplyRequest() {
        }
        
        public MultiplyRequest(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class MultiplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double result;
        
        public MultiplyResponse() {
        }
        
        public MultiplyResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class SubtractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public SubtractRequest() {
        }
        
        public SubtractRequest(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class SubtractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double result;
        
        public SubtractResponse() {
        }
        
        public SubtractResponse(double result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : global::Microsoft.Samples.NetTcp.BattleNet.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<global::Microsoft.Samples.NetTcp.BattleNet.ICalculator>, global::Microsoft.Samples.NetTcp.BattleNet.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.AddResponse global::Microsoft.Samples.NetTcp.BattleNet.ICalculator.Add(global::Microsoft.Samples.NetTcp.BattleNet.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public double Add(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.AddRequest inValue = new global::Microsoft.Samples.NetTcp.BattleNet.AddRequest();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.AddResponse retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.ICalculator)(this)).Add(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.DivideResponse global::Microsoft.Samples.NetTcp.BattleNet.ICalculator.Divide(global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest request) {
            return base.Channel.Divide(request);
        }
        
        public double Divide(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest inValue = new global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.DivideResponse retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.ICalculator)(this)).Divide(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.MultiplyResponse global::Microsoft.Samples.NetTcp.BattleNet.ICalculator.Multiply(global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest request) {
            return base.Channel.Multiply(request);
        }
        
        public double Multiply(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest inValue = new global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.MultiplyResponse retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.ICalculator)(this)).Multiply(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.SubtractResponse global::Microsoft.Samples.NetTcp.BattleNet.ICalculator.Subtract(global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest request) {
            return base.Channel.Subtract(request);
        }
        
        public double Subtract(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest inValue = new global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.SubtractResponse retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.ICalculator)(this)).Subtract(inValue);
            return retVal.result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Battle.net", ConfigurationName="BattleNet.IEcho", CallbackContract=typeof(global::Microsoft.Samples.NetTcp.BattleNet.IEchoCallback))]
    public interface IEcho {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoCallback {
        
        // CODEGEN: Generating message contract since the wrapper name (PingRequest) of message PingSolicit does not match the default value (Ping)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/IEcho/Ping", ReplyAction="http://Battle.net/IEcho/PingResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.PingResponse Ping(global::Microsoft.Samples.NetTcp.BattleNet.PingSolicit request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class PingSolicit {
        
        public PingSolicit() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class PingResponse {
        
        public PingResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoChannel : global::Microsoft.Samples.NetTcp.BattleNet.IEcho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoClient : System.ServiceModel.DuplexClientBase<global::Microsoft.Samples.NetTcp.BattleNet.IEcho>, global::Microsoft.Samples.NetTcp.BattleNet.IEcho {
        
        public EchoClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public EchoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public EchoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Battle.net", ConfigurationName="BattleNet.INativeCalculator")]
    public interface INativeCalculator {
        
        // CODEGEN: Generating message contract since the wrapper name (CNativeCalculatorRequest) of message AddRequest does not match the default value (Add)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/INativeCalculator/Add", ReplyAction="http://Battle.net/INativeCalculator/AddResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.AddResponse1 Add(global::Microsoft.Samples.NetTcp.BattleNet.AddRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (CNativeCalculatorRequest) of message DivideRequest does not match the default value (Divide)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/INativeCalculator/Divide", ReplyAction="http://Battle.net/INativeCalculator/DivideResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.DivideResponse1 Divide(global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (CNativeCalculatorRequest) of message MultiplyRequest does not match the default value (Multiply)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/INativeCalculator/Multiply", ReplyAction="http://Battle.net/INativeCalculator/MultiplyResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.MultiplyResponse1 Multiply(global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest1 request);
        
        // CODEGEN: Generating message contract since the wrapper name (CNativeCalculatorRequest) of message SubtractRequest does not match the default value (Subtract)
        [System.ServiceModel.OperationContractAttribute(Action="http://Battle.net/INativeCalculator/Subtract", ReplyAction="http://Battle.net/INativeCalculator/SubtractResponse")]
        global::Microsoft.Samples.NetTcp.BattleNet.SubtractResponse1 Subtract(global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class AddRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public AddRequest1() {
        }
        
        public AddRequest1(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class AddResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double response;
        
        public AddResponse1() {
        }
        
        public AddResponse1(double response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class DivideRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public DivideRequest1() {
        }
        
        public DivideRequest1(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class DivideResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double response;
        
        public DivideResponse1() {
        }
        
        public DivideResponse1(double response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class MultiplyRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public MultiplyRequest1() {
        }
        
        public MultiplyRequest1(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class MultiplyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double response;
        
        public MultiplyResponse1() {
        }
        
        public MultiplyResponse1(double response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorRequest", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class SubtractRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=1)]
        public double param2;
        
        public SubtractRequest1() {
        }
        
        public SubtractRequest1(double param1, double param2) {
            this.param1 = param1;
            this.param2 = param2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CNativeCalculatorResponse", WrapperNamespace="http://Battle.net", IsWrapped=true)]
    public partial class SubtractResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Battle.net", Order=0)]
        public double response;
        
        public SubtractResponse1() {
        }
        
        public SubtractResponse1(double response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INativeCalculatorChannel : global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NativeCalculatorClient : System.ServiceModel.ClientBase<global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator>, global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator {
        
        public NativeCalculatorClient() {
        }
        
        public NativeCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NativeCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NativeCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NativeCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.AddResponse1 global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator.Add(global::Microsoft.Samples.NetTcp.BattleNet.AddRequest1 request) {
            return base.Channel.Add(request);
        }
        
        public double Add(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.AddRequest1 inValue = new global::Microsoft.Samples.NetTcp.BattleNet.AddRequest1();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.AddResponse1 retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator)(this)).Add(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.DivideResponse1 global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator.Divide(global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest1 request) {
            return base.Channel.Divide(request);
        }
        
        public double Divide(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest1 inValue = new global::Microsoft.Samples.NetTcp.BattleNet.DivideRequest1();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.DivideResponse1 retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator)(this)).Divide(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.MultiplyResponse1 global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator.Multiply(global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest1 request) {
            return base.Channel.Multiply(request);
        }
        
        public double Multiply(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest1 inValue = new global::Microsoft.Samples.NetTcp.BattleNet.MultiplyRequest1();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.MultiplyResponse1 retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator)(this)).Multiply(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Microsoft.Samples.NetTcp.BattleNet.SubtractResponse1 global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator.Subtract(global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest1 request) {
            return base.Channel.Subtract(request);
        }
        
        public double Subtract(double param1, double param2) {
            global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest1 inValue = new global::Microsoft.Samples.NetTcp.BattleNet.SubtractRequest1();
            inValue.param1 = param1;
            inValue.param2 = param2;
            global::Microsoft.Samples.NetTcp.BattleNet.SubtractResponse1 retVal = ((global::Microsoft.Samples.NetTcp.BattleNet.INativeCalculator)(this)).Subtract(inValue);
            return retVal.response;
        }
    }
}
